#!/bin/bash

# Get all abbreviations in a single line
get_all_abbreviations() {
    echo "Capacity=cap"
    echo "Connection=conn"
    echo "Dashboard=db"
    echo "Datamart=dm"
    echo "DataPipeline=pip"
    echo "Domain=dom"
    echo "Environment=env"
    echo "Eventhouse=eh"
    echo "Eventstream=es"
    echo "ExternalDataShare=eds"
    echo "Gateway=gw"
    echo "KQLDashboard=kd"
    echo "KQLDatabase=kdb"
    echo "KQLQueryset=kqs"
    echo "Lakehouse=lh"
    echo "ManagedIdentity=mi"
    echo "ManagedPrivateEndpoint=mpe"
    echo "MirroredDatabase=mdb"
    echo "MLExperiment=mle"
    echo "MLModel=mlm"
    echo "Notebook=nb"
    echo "PaginatedReport=pr"
    echo "Reflex=rfx"
    echo "Report=rpt"
    echo "SemanticModel=sm"
    echo "SparkJobDefinition=sjd"
    echo "SparkPool=sp"
    echo "Warehouse=wh"
    echo "Workspace=ws"
}